application: hausbrew
version: jon
runtime: python27
api_version: 1

default_expiration: "5d 12h"

threadsafe: false

libraries:
- name: numpy
  version: latest
- name: webapp2
  version: latest
- name: django
  version: "1.3"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gz
- ^(.*/)?.*\.bak

handlers:
- url: /
  script: main.app
- url: /index.html
  script: main.app

# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory. Note that static_dir handlers do not use a
# regular expression for the URL pattern, only a prefix.
- url: /style
  static_dir: style
- url: /images
  static_dir: images
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

##UNTESTED models##
#description
- url: /(.*?)_description.html
  script: \1/\1_description.py
#input
- url: /(.*?)_input.html
  script: \1/\1_input.py
#output
- url: /(.*?)_output.html
  script: \1/\1_output.py  
#algorithms
- url: /(.*?)_algorithms.html
  script: \1/\1_algorithm.py    
#references
- url: /(.*?)_references.html
  script: \1/\1_references.py 

#file not found
- url: /.*
  script: file_not_found.py
